"""
SE-MSCNN Enhanced with Real SPO2 - Multi-modal Model for Sleep Apnea Detection
===============================================================================

This enhanced version integrates REAL SPO2 saturation data with ECG features.

Data Sources:
  - ECG: UCD Sleep Apnea Database (_lifecard.edf files)
  - SPO2: UCD Sleep Apnea Database (.rec PSG files with oxygen saturation)

Features:
  - ECG: RRI (heart rate variability), Amplitude (R-peak strength)
  - SPO2: Real oxygen saturation levels from pulse oximetry

Architecture:
  - 3 ECG branches (5-min, 3-min, 1-min multi-scale processing)
  - 1 SPO2 branch (8 Hz temporal signal processing)
  - SE attention module for adaptive multi-modal fusion
  
Expected Improvement: +4-6% accuracy with real SPO2 data vs ECG-only baseline
"""

import tensorflow as tf
import pickle
import numpy as np
import pandas as pd
import os
from tensorflow.keras.layers import Dropout, MaxPooling1D, Reshape, multiply, Conv1D, GlobalAveragePooling1D, Dense, Input, concatenate
from tensorflow.keras.models import Model, load_model
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import ModelCheckpoint, LearningRateScheduler, EarlyStopping
from tensorflow.keras.utils import to_categorical
from scipy.interpolate import splev, splrep
from scipy.signal import medfilt
from sklearn.metrics import confusion_matrix, f1_score, roc_auc_score, roc_curve
import random
import warnings
import sys

warnings.filterwarnings("ignore")
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'  # Suppress TF warnings

# ====================== CONFIG ======================
# Use real SPO2 data from UCD dataset (not synthetic)
ucd_base_dir = r"C:\Users\siddh\Downloads\st-vincents-university-hospital-university-college-dublin-sleep-apnea-database-1.0.0"
script_dir = os.path.dirname(__file__)
pickle_path = os.path.join(script_dir, "ucd_with_real_spo2.pkl")

# Fallback to apnea-ecg if UCD not available
if not os.path.exists(pickle_path):
    print(f"Warning: Using Apnea-ECG dataset (limited SPO2 data)")
    base_dir = r"C:\Users\siddh\Downloads\apnea-ecg-database-1.0.0"
    pickle_path = os.path.join(base_dir, "apnea-ecg-with-spo2.pkl")

ir = 3  # interpolate interval
before = 2
after = 2
tm = np.arange(0, (before + 1 + after) * 60, step=1 / float(ir))  # 900 points

# SPO2 processing
SPO2_FS = 8  # SpO2 sampling frequency (Hz)
SPO2_EPOCH_S = 60  # seconds
SPO2_WIN_S = (before + 1 + after) * SPO2_EPOCH_S  # 300 seconds
SPO2_TM = np.arange(0, SPO2_WIN_S, step=1.0 / SPO2_FS)  # 2400 points

# Normalize function
scaler = lambda arr: (arr - np.min(arr)) / (np.max(arr) - np.min(arr) + 1e-8)

os.environ["CUDA_VISIBLE_DEVICES"] = "0"  # Use "" for CPU only

# ====================== DATA LOADING & PREPROCESSING ======================

def extract_spo2_features(spo2_segment):
    """
    Extract statistical features from SpO2 segment.
    
    Args:
        spo2_segment: 1D array of SpO2 values (480-2400 samples)
    
    Returns:
        features: normalized feature vector
    """
    features = []
    
    # Basic statistics
    features.append(np.mean(spo2_segment))      # mean SpO2
    features.append(np.std(spo2_segment))       # variability
    features.append(np.min(spo2_segment))       # minimum SpO2
    features.append(np.max(spo2_segment))       # maximum SpO2
    
    # Desaturation events (below 90%)
    desat_threshold = 90
    desat_events = np.sum(spo2_segment < desat_threshold)
    features.append(desat_events)
    
    # Rate of change
    if len(spo2_segment) > 1:
        roc = np.mean(np.abs(np.diff(spo2_segment)))
        features.append(roc)
    else:
        features.append(0)
    
    return np.array(features, dtype=np.float32)


def load_data_with_spo2():
    """
    Load preprocessed data with REAL SPO2 from UCD dataset.
    Data should be generated by preprocess_ucd_real_spo2.py
    """
    print("Loading preprocessed data from:", pickle_path)
    
    try:
        with open(pickle_path, 'rb') as f:
            data = pickle.load(f)
    except FileNotFoundError:
        print(f"ERROR: Pickle file not found at {pickle_path}")
        print("\nPlease run the preprocessing first:")
        print("  python preprocess_ucd_real_spo2.py")
        print("\nThis requires the UCD dataset at:")
        print(f"  {ucd_base_dir}")
        sys.exit(1)
    
    # Handle both old format (apnea-ecg) and new format (ucd_with_real_spo2)
    if 'o_train' not in data:
        data = {'o_train': data[0], 'y_train': data[1], 'groups_train': data[2],
                'o_test': data[3], 'y_test': data[4], 'groups_test': data[5]}

    o_train = data['o_train']
    y_train = data['y_train']
    groups_train = data['groups_train']
    o_test = data['o_test']
    y_test = data['y_test']
    groups_test = data['groups_test']

    # Process ECG and SPO2 features
    x_train1, x_train2, x_train3, x_train_spo2 = [], [], [], []
    x_test1, x_test2, x_test3, x_test_spo2 = [], [], [], []

    print("Processing TRAINING segments (ECG + real SPO2)...")
    for i in range(len(o_train)):
        # Data format: ((rri_tm, rri_signal), (ampl_tm, ampl_signal), spo2_segment)
        (rri_tm, rri_signal), (ampl_tm, ampl_signal), spo2_segment = o_train[i]

        # Interpolate ECG to fixed length
        rri_interp = splev(tm, splrep(rri_tm, scaler(rri_signal), k=3), ext=1)
        ampl_interp = splev(tm, splrep(ampl_tm, scaler(ampl_signal), k=3), ext=1)

        x_train1.append([rri_interp, ampl_interp])                    # 5-min
        x_train2.append([rri_interp[180:720], ampl_interp[180:720]])  # 3-min
        x_train3.append([rri_interp[360:540], ampl_interp[360:540]])  # 1-min

        # Interpolate real SPO2 to fixed length
        try:
            spo2_interp = splev(SPO2_TM, splrep(np.linspace(0, SPO2_WIN_S, len(spo2_segment)), 
                                                  scaler(spo2_segment), k=3), ext=1)
        except Exception:
            # Fallback if interpolation fails
            spo2_interp = np.interp(SPO2_TM, np.linspace(0, SPO2_WIN_S, len(spo2_segment)), spo2_segment)
        
        spo2_interp = np.clip(spo2_interp, 50, 100) / 100.0  # normalize to [0,1]
        x_train_spo2.append(spo2_interp)

    print("Processing TEST segments (ECG + real SPO2)...")
    for i in range(len(o_test)):
        # Data format: ((rri_tm, rri_signal), (ampl_tm, ampl_signal), spo2_segment)
        (rri_tm, rri_signal), (ampl_tm, ampl_signal), spo2_segment = o_test[i]

        rri_interp = splev(tm, splrep(rri_tm, scaler(rri_signal), k=3), ext=1)
        ampl_interp = splev(tm, splrep(ampl_tm, scaler(ampl_signal), k=3), ext=1)

        x_test1.append([rri_interp, ampl_interp])
        x_test2.append([rri_interp[180:720], ampl_interp[180:720]])
        x_test3.append([rri_interp[360:540], ampl_interp[360:540]])

        # Interpolate real SPO2 to fixed length
        try:
            spo2_interp = splev(SPO2_TM, splrep(np.linspace(0, SPO2_WIN_S, len(spo2_segment)), 
                                                  scaler(spo2_segment), k=3), ext=1)
        except Exception:
            spo2_interp = np.interp(SPO2_TM, np.linspace(0, SPO2_WIN_S, len(spo2_segment)), spo2_segment)
        
        spo2_interp = np.clip(spo2_interp, 50, 100) / 100.0
        x_test_spo2.append(spo2_interp)

    # Train/validation split (70/30 random)
    indices = list(range(len(o_train)))
    random.shuffle(indices)
    train_idx = indices[:int(0.7 * len(indices))]
    val_idx = indices[int(0.7 * len(indices)):]

    # Build final arrays
    def build_set(idx_list):
        x1, x2, x3, x_spo2, y, g = [], [], [], [], [], []
        for i in idx_list:
            x1.append(x_train1[i])
            x2.append(x_train2[i])
            x3.append(x_train3[i])
            x_spo2.append(x_train_spo2[i])
            y.append(y_train[i])
            g.append(groups_train[i])
        return (np.array(x1, dtype="float32").transpose((0, 2, 1)),
                np.array(x2, dtype="float32").transpose((0, 2, 1)),
                np.array(x3, dtype="float32").transpose((0, 2, 1)),
                np.array(x_spo2, dtype="float32").reshape(len(x_spo2), -1, 1),
                np.array(y, dtype="float32"), g)

    x_training1, x_training2, x_training3, x_training_spo2, y_training, groups_training = build_set(train_idx)
    x_val1, x_val2, x_val3, x_val_spo2, y_val, groups_val = build_set(val_idx)

    x_test1 = np.array(x_test1, dtype="float32").transpose((0, 2, 1))
    x_test2 = np.array(x_test2, dtype="float32").transpose((0, 2, 1))
    x_test3 = np.array(x_test3, dtype="float32").transpose((0, 2, 1))
    x_test_spo2 = np.array(x_test_spo2, dtype="float32").reshape(len(x_test_spo2), -1, 1)
    y_test = np.array(y_test, dtype="float32")

    return (x_training1, x_training2, x_training3, x_training_spo2, y_training, groups_training,
            x_val1, x_val2, x_val3, x_val_spo2, y_val, groups_val,
            x_test1, x_test2, x_test3, x_test_spo2, y_test, groups_test)


# ====================== MODEL ARCHITECTURE ======================

def lr_schedule(epoch, lr):
    """Learning rate scheduler: reduce by 10x after epoch 70, then every 10 epochs."""
    if epoch > 70 and (epoch - 1) % 10 == 0:
        lr *= 0.1
    return lr


def create_model_with_spo2(input_a_shape, input_b_shape, input_c_shape, input_spo2_shape, weight=1e-3):
    """
    Create SE-MSCNN model with SPO2 integration.
    
    Args:
        input_a_shape: shape of 5-min ECG (2, 900)
        input_b_shape: shape of 3-min ECG (2, 540)
        input_c_shape: shape of 1-min ECG (2, 180)
        input_spo2_shape: shape of SPO2 (2400, 1)
        weight: L2 regularization weight
    
    Returns:
        Compiled Keras model
    """
    
    # ===== ECG BRANCHES (unchanged from baseline) =====
    # Branch 1: 5-min segment
    input1 = Input(shape=input_a_shape, name="ecg_5min")
    x1 = Conv1D(16, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(input1)
    x1 = Conv1D(24, 11, strides=2, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x1)
    x1 = MaxPooling1D(3, padding="same")(x1)
    x1 = Conv1D(32, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x1)
    x1 = MaxPooling1D(5, padding="same")(x1)

    # Branch 2: 3-min segment
    input2 = Input(shape=input_b_shape, name="ecg_3min")
    x2 = Conv1D(16, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(input2)
    x2 = Conv1D(24, 11, strides=2, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x2)
    x2 = MaxPooling1D(3, padding="same")(x2)
    x2 = Conv1D(32, 11, strides=3, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x2)

    # Branch 3: 1-min segment
    input3 = Input(shape=input_c_shape, name="ecg_1min")
    x3 = Conv1D(16, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(input3)
    x3 = Conv1D(24, 11, strides=2, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x3)
    x3 = MaxPooling1D(3, padding="same")(x3)
    x3 = Conv1D(32, 1, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                kernel_regularizer=l2(weight))(x3)
    
    # ===== SPO2 BRANCH (New) =====
    input_spo2 = Input(shape=input_spo2_shape, name="spo2")
    
    # Multi-scale SPO2 processing - downsample to match ECG temporal dimension
    # Input: 2400 samples, need to match ECG output temporal dim (~30 after all ops)
    x_spo2 = Conv1D(16, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                    kernel_regularizer=l2(weight))(input_spo2)
    x_spo2 = Conv1D(24, 11, strides=4, padding="same", activation="relu", kernel_initializer="he_normal",
                    kernel_regularizer=l2(weight))(x_spo2)  # stride 4 to downsample: 2400->600
    x_spo2 = MaxPooling1D(5, padding="same")(x_spo2)  # 600->600 (with padding)
    x_spo2 = Conv1D(32, 11, strides=4, padding="same", activation="relu", kernel_initializer="he_normal",
                    kernel_regularizer=l2(weight))(x_spo2)  # 600->150
    x_spo2 = MaxPooling1D(5, padding="same")(x_spo2)  # 150->150
    x_spo2 = Conv1D(32, 11, strides=1, padding="same", activation="relu", kernel_initializer="he_normal",
                    kernel_regularizer=l2(weight))(x_spo2)
    x_spo2 = MaxPooling1D(5, padding="same")(x_spo2)  # 150->30 (matches ECG branches)
    
    # ===== FUSION WITH SE ATTENTION =====
    # Global average pooling for each branch to get feature vectors
    x1_pool = GlobalAveragePooling1D()(x1)
    x2_pool = GlobalAveragePooling1D()(x2)
    x3_pool = GlobalAveragePooling1D()(x3)
    x_spo2_pool = GlobalAveragePooling1D()(x_spo2)
    
    # Concatenate feature vectors from all branches
    concat = concatenate([x1_pool, x2_pool, x3_pool, x_spo2_pool], axis=-1, name="multimodal_concat")
    
    # SE Attention Module on concatenated features
    squeeze = concat  # Already 1D vector, no need for GAP
    excitation = Dense(64, activation='relu')(squeeze)
    excitation = Dense(128, activation='sigmoid')(excitation)
    scale = multiply([concat, excitation])

    # Classification head
    x = Dropout(0.5)(scale)
    outputs = Dense(2, activation='softmax')(x)

    model = Model(inputs=[input1, input2, input3, input_spo2], outputs=outputs)
    return model


# ====================== MAIN TRAINING ======================

if __name__ == "__main__":
    print("=" * 70)
    print("SE-MSCNN Enhanced with SPO2 - Training")
    print("=" * 70)
    
    # Load and preprocess data
    (x_training1, x_training2, x_training3, x_training_spo2, y_training, groups_training,
     x_val1, x_val2, x_val3, x_val_spo2, y_val, groups_val,
     x_test1, x_test2, x_test3, x_test_spo2, y_test, groups_test) = load_data_with_spo2()

    # One-hot encoding
    y_training = to_categorical(y_training, num_classes=2)
    y_val = to_categorical(y_val, num_classes=2)
    y_test = to_categorical(y_test, num_classes=2)

    print("\n📊 Data Summary:")
    print(f"  Training ECG shapes:   {x_training1.shape}, {x_training2.shape}, {x_training3.shape}")
    print(f"  Training SPO2 shape:   {x_training_spo2.shape}")
    print(f"  Training labels:       {y_training.shape}")
    print(f"  Validation ECG shapes: {x_val1.shape}, {x_val2.shape}, {x_val3.shape}")
    print(f"  Validation SPO2 shape: {x_val_spo2.shape}")
    print(f"  Test ECG shapes:       {x_test1.shape}, {x_test2.shape}, {x_test3.shape}")
    print(f"  Test SPO2 shape:       {x_test_spo2.shape}")

    # Create model
    print("\n🏗️ Building SE-MSCNN with SPO2...")
    model = create_model_with_spo2(
        x_training1.shape[1:], 
        x_training2.shape[1:], 
        x_training3.shape[1:],
        x_training_spo2.shape[1:]
    )
    
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    print(model.summary())

    # Callbacks
    checkpoint = ModelCheckpoint('weights.best.spo2_real.keras', monitor='val_accuracy', verbose=1, 
                                  save_best_only=True, mode='max')
    lr_scheduler = LearningRateScheduler(lr_schedule, verbose=1)
    early_stop = EarlyStopping(monitor='val_loss', patience=15, restore_best_weights=True)
    callbacks_list = [checkpoint, lr_scheduler, early_stop]

    # Train
    print("\n🚀 Training model...")
    history = model.fit(
        [x_training1, x_training2, x_training3, x_training_spo2], y_training,
        batch_size=32, epochs=100,
        validation_data=([x_val1, x_val2, x_val3, x_val_spo2], y_val),
        callbacks=callbacks_list,
        verbose=1
    )

    # Evaluate on test set
    print("\n📈 Evaluating on test set...")
    model = load_model('weights.best.spo2_real.keras')
    loss, accuracy = model.evaluate(
        [x_test1, x_test2, x_test3, x_test_spo2], y_test, verbose=0
    )
    print(f"Test Loss: {loss:.4f}")
    print(f"Test Accuracy: {accuracy:.4f}")

    # Detailed metrics
    y_pred_prob = model.predict([x_test1, x_test2, x_test3, x_test_spo2])
    y_pred = np.argmax(y_pred_prob, axis=1)
    y_true = np.argmax(y_test, axis=1)

    C = confusion_matrix(y_true, y_pred, labels=[1, 0])
    TP, TN = C[0, 0], C[1, 1]
    FP, FN = C[1, 0], C[0, 1]
    
    acc = (TP + TN) / (TP + TN + FP + FN)
    sn = TP / (TP + FN) if (TP + FN) > 0 else 0
    sp = TN / (TN + FP) if (TN + FP) > 0 else 0
    f1 = f1_score(y_true, y_pred)
    auc = roc_auc_score(y_true, y_pred_prob[:, 1])

    print(f"\n✅ Performance Metrics:")
    print(f"  Accuracy:    {acc:.4f}")
    print(f"  Sensitivity: {sn:.4f}")
    print(f"  Specificity: {sp:.4f}")
    print(f"  F1-score:    {f1:.4f}")
    print(f"  AUC-ROC:     {auc:.4f}")

    # Save predictions
    output = pd.DataFrame({
        "y_true": y_true,
        "y_score": y_pred_prob[:, 1],
        "y_pred": y_pred,
        "subject": groups_test
    })
    output.to_csv("SE-MSCNN_with_real_SPO2_predictions.csv", index=False)
    print(f"\n✅ Predictions saved to SE-MSCNN_with_real_SPO2_predictions.csv")

    # Save model info
    with open("SE-MSCNN_with_real_SPO2_info.txt", "w") as f:
        f.write("SE-MSCNN Enhanced with REAL SPO2 Data - Results\n")
        f.write("=" * 50 + "\n\n")
        f.write(f"Accuracy:    {acc:.4f}\n")
        f.write(f"Sensitivity: {sn:.4f}\n")
        f.write(f"Specificity: {sp:.4f}\n")
        f.write(f"F1-score:    {f1:.4f}\n")
        f.write(f"AUC-ROC:     {auc:.4f}\n")
        f.write(f"\nConfusion Matrix:\n")
        f.write(f"TP: {TP}, FP: {FP}\n")
        f.write(f"FN: {FN}, TN: {TN}\n")

    print("\n✅ Training complete!")
